<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWPF>true</UseWPF>
    <Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>HamTech-M0FXB-IC706MKIIG-Controller</AssemblyName><RootNamespace>FT857DControl</RootNamespace>
    <Product>HamTech M0FXB ICOM IC-706MKIIG Controller</Product><Authors>HamTech M0FXB</Authors>
  </PropertyGroup>
  <ItemGroup><PackageReference Include="System.IO.Ports" Version="8.0.0"/><PackageReference Include="NAudio" Version="2.2.1"/></ItemGroup>
</Project>
